### PR TITLE
Englishify readme

### PR DESCRIPTION
**Pull request by wswoodruff**
Also, the trailing comma in the config.json example caused a sneaky JSON parse error. It said something about all properties needing to be string literals, so I was debugging that but really the trailing comma was telling JSON.parse that we were trying to specify another property. Anyway, removing the comma fixes it!

### CODE REVIEW

**Comment by wswoodruff** [comment]
I think that apache fixed the "cordova-plugin-file" plugin for getting readonly access Android, since it works for me.

**Comment by wswoodruff** [comment]
Oops, sorry didn't mean to close it

**Comment by mnill** [comment]
Hi! Thank for pull request!
Trailing comma and comments in example  json is really my terrible mistake :-(

I'm just needs to test cordova plugin file, before merge fixes.

**Comment by mnill** [comment]
Are you sure about file plugin?
It is still not work correctly for me.

May be you just already have valid cache, create by my version of plugin?
Can you please increment version in server config.json and try to relaunch the app?

**Comment by wswoodruff** [comment]
mnill I'm going to verify this later on today to make sure. I think I had to grab the plugin from their github page, but I'll make sure and let you know.

**Comment by mnill** [comment]
my fork installs with the same name

**Comment by wswoodruff** [comment]
Hmm, I think you're right it was probably in my cache. If I find out otherwise later, I'll provide something more detailed to reproduce. Thanks for your work on this awesome updater plugin and for extending the cordova file plugin!

**Comment by wswoodruff** [comment]
I put back the link to your fork of cordova-plugin-file in the readme

**Pull request merged**
